<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Premiere migration du depot : les deux tables de la couche de securite.
 *
 * ECRITE A LA MAIN (le worktree de livraison n'a ni dependances ni base, donc
 * pas de `doctrine:migrations:diff`). Les noms d'index et de contrainte sont
 * donc poses EXPLICITEMENT ici ET dans les attributs des entites : sans cela,
 * Doctrine fabriquerait ses propres noms (`UNIQ_<hash>`) et le premier `diff`
 * ulterieur proposerait de renommer des index qui vont deja bien.
 *
 * `INT GENERATED BY DEFAULT AS IDENTITY` et non une sequence : c'est ce que
 * demande `identity_generation_preferences` dans config/packages/doctrine.yaml.
 */
final class Version20261007200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Couche de securite : societes clientes (client) et comptes utilisateurs (app_user).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE client (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                code VARCHAR(32) NOT NULL,
                name VARCHAR(180) NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_client_code ON client (code)');

        // « user » est un mot reserve de PostgreSQL : la table s'appelle
        // app_user (voir l'attribut ORM\Table de App\Entity\User).
        $this->addSql(<<<'SQL'
            CREATE TABLE app_user (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                client_id INT NOT NULL,
                email VARCHAR(180) NOT NULL,
                first_name VARCHAR(80) NOT NULL,
                last_name VARCHAR(80) NOT NULL,
                is_active BOOLEAN NOT NULL,
                roles JSON NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_email ON app_user (email)');
        $this->addSql('CREATE INDEX idx_app_user_client ON app_user (client_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE app_user
                ADD CONSTRAINT fk_app_user_client
                FOREIGN KEY (client_id) REFERENCES client (id)
                NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT fk_app_user_client');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE client');
    }
}
